-- DDL H2 (MEMORY) PARA BASE RECUPERATORIO

-- =========================================================
-- SECUENCIAS
-- =========================================================

CREATE SEQUENCE SEQ_ARTIST_ID          START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALBUM_ID           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPLOYEE_ID        START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CUSTOMER_ID        START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GENRE_ID           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INVOICE_ID         START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEDIA_TYPE_ID      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PLAYLIST_ID        START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRACK_ID           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INVOICE_LINE_ID    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PLAYLIST_TRACK_ID  START WITH 1 INCREMENT BY 1;

-- =========================================================
-- TABLA ARTISTS
-- =========================================================

CREATE TABLE ARTISTS
(
    ARTIST_ID INTEGER      NOT NULL DEFAULT NEXT VALUE FOR SEQ_ARTIST_ID,
    NAME      VARCHAR(120),
    CONSTRAINT PK_ARTISTS PRIMARY KEY (ARTIST_ID)
);

-- =========================================================
-- TABLA ALBUMS
-- =========================================================

CREATE TABLE ALBUMS
(
    ALBUM_ID   INTEGER       NOT NULL DEFAULT NEXT VALUE FOR SEQ_ALBUM_ID,
    TITLE      VARCHAR(160)  NOT NULL,
    ARTIST_ID  INTEGER       NOT NULL,
    CONSTRAINT PK_ALBUMS PRIMARY KEY (ALBUM_ID),
    CONSTRAINT FK_ALBUM_ARTIST
        FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS (ARTIST_ID)
);

CREATE INDEX IFK_ALBUM_ARTIST_ID
    ON ALBUMS (ARTIST_ID);

-- =========================================================
-- TABLA EMPLOYEES
-- =========================================================

CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID  INTEGER       NOT NULL DEFAULT NEXT VALUE FOR SEQ_EMPLOYEE_ID,
    LAST_NAME    VARCHAR(20)   NOT NULL,
    FIRST_NAME   VARCHAR(20)   NOT NULL,
    TITLE        VARCHAR(30),
    REPORTS_TO   INTEGER,
    BIRTH_DATE   DATE,
    HIRE_DATE    DATE,
    ADDRESS      VARCHAR(70),
    CITY         VARCHAR(40),
    STATE        VARCHAR(40),
    COUNTRY      VARCHAR(40),
    POSTAL_CODE  VARCHAR(10),
    PHONE        VARCHAR(24),
    FAX          VARCHAR(24),
    EMAIL        VARCHAR(60),
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_EMPLOYEE_REPORTS_TO
        FOREIGN KEY (REPORTS_TO) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

CREATE INDEX IFK_EMPLOYEE_REPORTS_TO
    ON EMPLOYEES (REPORTS_TO);

-- =========================================================
-- TABLA CUSTOMERS
-- =========================================================

CREATE TABLE CUSTOMERS
(
    CUSTOMER_ID    INTEGER       NOT NULL DEFAULT NEXT VALUE FOR SEQ_CUSTOMER_ID,
    FIRST_NAME     VARCHAR(40)   NOT NULL,
    LAST_NAME      VARCHAR(20)   NOT NULL,
    COMPANY        VARCHAR(80),
    ADDRESS        VARCHAR(70),
    CITY           VARCHAR(40),
    STATE          VARCHAR(40),
    COUNTRY        VARCHAR(40),
    POSTAL_CODE    VARCHAR(10),
    PHONE          VARCHAR(24),
    FAX            VARCHAR(24),
    EMAIL          VARCHAR(60)   NOT NULL,
    SUPPORT_REP_ID INTEGER,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT FK_CUSTOMER_SUPPORT_REP
        FOREIGN KEY (SUPPORT_REP_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

CREATE INDEX IFK_CUSTOMER_SUPPORT_REP_ID
    ON CUSTOMERS (SUPPORT_REP_ID);

-- =========================================================
-- TABLA GENRES
-- =========================================================

CREATE TABLE GENRES
(
    GENRE_ID INTEGER      NOT NULL DEFAULT NEXT VALUE FOR SEQ_GENRE_ID,
    NAME     VARCHAR(120),
    CONSTRAINT PK_GENRES PRIMARY KEY (GENRE_ID)
);

-- =========================================================
-- TABLA INVOICES
-- =========================================================

CREATE TABLE INVOICES
(
    INVOICE_ID          INTEGER        NOT NULL DEFAULT NEXT VALUE FOR SEQ_INVOICE_ID,
    CUSTOMER_ID         INTEGER        NOT NULL,
    INVOICE_DATE        DATE           NOT NULL,
    BILLING_ADDRESS     VARCHAR(70),
    BILLING_CITY        VARCHAR(40),
    BILLING_STATE       VARCHAR(40),
    BILLING_COUNTRY     VARCHAR(40),
    BILLING_POSTAL_CODE VARCHAR(10),
    TOTAL               NUMERIC(10, 2) NOT NULL,
    CONSTRAINT PK_INVOICES PRIMARY KEY (INVOICE_ID),
    CONSTRAINT FK_INVOICE_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

CREATE INDEX IFK_INVOICE_CUSTOMER_ID
    ON INVOICES (CUSTOMER_ID);

-- =========================================================
-- TABLA MEDIA_TYPES
-- =========================================================

CREATE TABLE MEDIA_TYPES
(
    MEDIA_TYPE_ID INTEGER      NOT NULL DEFAULT NEXT VALUE FOR SEQ_MEDIA_TYPE_ID,
    NAME          VARCHAR(120),
    CONSTRAINT PK_MEDIA_TYPES PRIMARY KEY (MEDIA_TYPE_ID)
);

-- =========================================================
-- TABLA PLAYLISTS
-- =========================================================

CREATE TABLE PLAYLISTS
(
    PLAYLIST_ID INTEGER      NOT NULL DEFAULT NEXT VALUE FOR SEQ_PLAYLIST_ID,
    NAME        VARCHAR(120),
    CONSTRAINT PK_PLAYLISTS PRIMARY KEY (PLAYLIST_ID)
);

-- =========================================================
-- TABLA TRACKS
-- =========================================================

CREATE TABLE TRACKS
(
    TRACK_ID      INTEGER        NOT NULL DEFAULT NEXT VALUE FOR SEQ_TRACK_ID,
    NAME          VARCHAR(200)   NOT NULL,
    ALBUM_ID      INTEGER,
    MEDIA_TYPE_ID INTEGER        NOT NULL,
    GENRE_ID      INTEGER,
    COMPOSER      VARCHAR(220),
    MILLISECONDS  INTEGER        NOT NULL,
    BYTES         INTEGER,
    UNIT_PRICE    NUMERIC(10, 2) NOT NULL,
    CONSTRAINT PK_TRACKS PRIMARY KEY (TRACK_ID),
    CONSTRAINT FK_TRACK_ALBUM
        FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS (ALBUM_ID),
    CONSTRAINT FK_TRACK_MEDIA_TYPE
        FOREIGN KEY (MEDIA_TYPE_ID) REFERENCES MEDIA_TYPES (MEDIA_TYPE_ID),
    CONSTRAINT FK_TRACK_GENRE
        FOREIGN KEY (GENRE_ID) REFERENCES GENRES (GENRE_ID)
);

CREATE INDEX IFK_TRACK_ALBUM_ID
    ON TRACKS (ALBUM_ID);

CREATE INDEX IFK_TRACK_MEDIA_TYPE_ID
    ON TRACKS (MEDIA_TYPE_ID);

CREATE INDEX IFK_TRACK_GENRE_ID
    ON TRACKS (GENRE_ID);

-- =========================================================
-- TABLA INVOICE_ITEMS
-- =========================================================

CREATE TABLE INVOICE_ITEMS
(
    INVOICE_LINE_ID INTEGER        NOT NULL DEFAULT NEXT VALUE FOR SEQ_INVOICE_LINE_ID,
    INVOICE_ID      INTEGER        NOT NULL,
    TRACK_ID        INTEGER        NOT NULL,
    UNIT_PRICE      NUMERIC(10, 2) NOT NULL,
    QUANTITY        INTEGER        NOT NULL,
    CONSTRAINT PK_INVOICE_ITEMS PRIMARY KEY (INVOICE_LINE_ID),
    CONSTRAINT FK_INVOICE_LINE_INVOICE
        FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES (INVOICE_ID),
    CONSTRAINT FK_INVOICE_LINE_TRACK
        FOREIGN KEY (TRACK_ID) REFERENCES TRACKS (TRACK_ID)
);

CREATE INDEX IFK_INVOICE_LINE_INVOICE_ID
    ON INVOICE_ITEMS (INVOICE_ID);

CREATE INDEX IFK_INVOICE_LINE_TRACK_ID
    ON INVOICE_ITEMS (TRACK_ID);

-- =========================================================
-- TABLA PLAYLIST_TRACK
-- =========================================================

CREATE TABLE PLAYLIST_TRACK
(
    PLAYLIST_TRACK_ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR SEQ_PLAYLIST_TRACK_ID,
    PLAYLIST_ID       INTEGER NOT NULL,
    TRACK_ID          INTEGER NOT NULL,
    CONSTRAINT PK_PLAYLIST_TRACK PRIMARY KEY (PLAYLIST_TRACK_ID),
    CONSTRAINT FK_PLAYLIST_TRACK_PLAYLIST
        FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLISTS (PLAYLIST_ID),
    CONSTRAINT FK_PLAYLIST_TRACK_TRACK
        FOREIGN KEY (TRACK_ID) REFERENCES TRACKS (TRACK_ID)
);

CREATE INDEX IFK_PLAYLIST_TRACK_TRACK_ID
    ON PLAYLIST_TRACK (TRACK_ID);
